### ISSUE TITLE
Memoize pagination calculations in useRepos hook

### ISSUE THREAD

**Issue by harunsmrkovic** [rubenmarcus/repo-search-github#1] opened 2024-01-16 09:32 UTC
Hey there 👋 

What do you think about using memoize for these pagination values in the useRepos hook, to improve rendering performance?

https://github.com/rubenmarcus/repo-search-github/blob/c8039b1d730da3d7f8adea843ead6cf697a133f6/src/hooks/useReposData.ts#L44-L52

**Comment by rubenmarcus** [comment] 2024-01-17 05:39
hey @harunsmrkovic  thanks for looking at the code.
The issue is that applying memoization here is useless, because github Api is called every time you change page and the repositoryCount object is inside each call, I could set a separate state where this value stays saved until a new topic is searched but theres two problems with this approach:

1 - number of repositories could get updated when you change pages and you dont get the new pages/repository numbers
2 - while changing topics I need to invalidate the totalRepos state and this was causing some issues on the pagination and requests of new topic pages

I think I need to think in a better approach where I can 
1 - check if totalRepos changed when user change pages
2 - maintain a good UX (not changing the pagination values on each request ) 

the solution I think is doing the totalRepos request outside the getRepos, maybe a new request so this data doesnt get updated all the time with every pagination call

**Comment by rubenmarcus** [comment] 2024-01-17 06:01
@harunsmrkovic  [fixed on this commit](https://github.com/rubenmarcus/repo-search-github/commit/ade4f01902183e3f1b61b99c83a2e7caac8a725c)

**Comment by harunsmrkovic** [comment] 2024-01-17 08:53
Hey @rubenmarcus, thanks for the quick reply!

I probably phrased my issue poorly, I apologize for that. I didn't mean to refer just to memoizing the `totalPages` variable, but instead all of the highlighted variables, such as `totalPages, maxVisiblePages, pages, startPage`.

Point of memoizing that I had in mind was avoiding the recalculations like `Array.from` and `Math`. No need to re-do it though, I just wanted to hear your thoughts about doing it.

However, the solution that you applied in the linked commit is very confusing and I don't understand what issue did it actually solve. Can you please explain what was the issue with having this count in the same query, and how did this resolve it?

**Comment by rubenmarcus** [comment] 2024-01-17 10:54
@harunsmrkovic  makes sense, memoized here https://github.com/rubenmarcus/repo-search-github/commit/57e51826350f967264165b459208ad5172793db7


it was trying to solve, due to repositoryCount comes from data, everytime I fetch a new data on the page change, it was updating repositoryCount ( as also the pagination calculation ) , so you had loading shimmers on the total repositories on top as also on the pagination numbers do to that

separating 2 queries made it repositoryCount only be updated when you change topic, not on every query call

**Closed as completed** 2024-01-17 11:20 UTC
